subscription metricsPerformed($url: String!) {
  metricsPerformed(url: $url) {
    lookupDuration
    fast
    lastStatus
    lastWasError
    mostFrequentStatus
    totalRequests
    totalDuration
    totalErrors
    averageServiceTime
    p50ServiceTime
    p90ServiceTime
    p95ServiceTime
    maxServiceTime
  }
}
